default:
  image: gitlab.ewi.tudelft.nl:4242/cse3100/admin/docker-ci-image-builder@sha256:e6251ef3d888ece30cb83d1d7cfcc7146589709058be10e3793a9f44a7a023c3


stages:
- build
- test

build:
  stage: build
  artifacts:
    expire_in: 4 weeks
  before_script:
  - cp -r ~/.cabal .
  - cp -r /dist-newstyle .
  - cabal v2-configure --enable-tests
  script:
  - cabal v2-build exe:jq-clone


from-upstream:
  stage: test
  artifacts:
    expire_in: 4 weeks
  before_script:
  - cp -r ~/.cabal .
  - cp -r /dist-newstyle .
  - cabal v2-configure --enable-tests
  script:
  - cabal test from-upstream

week3:
  stage: test
  artifacts:
    expire_in: 4 weeks
  before_script:
  - cp -r ~/.cabal .
  - cp -r /dist-newstyle .
  - cabal v2-configure --enable-tests
  script:
  - cabal test week3

week4:
  stage: test
  artifacts:
    expire_in: 4 weeks
  before_script:
  - cp -r ~/.cabal .
  - cp -r /dist-newstyle .
  - cabal v2-configure --enable-tests
  script:
  - cabal test week4

unit-tests:
  stage: test
  artifacts:
    expire_in: 4 weeks
  before_script:
  - cp -r ~/.cabal .
  - cp -r /dist-newstyle .
  - cabal v2-configure --enable-tests
  script:
  - cabal test unit-tests